## Documentation
# https://docs.astro.build/en/guides/deploy/github/

name: HEIG-VD UPInfoIM Course GitHub Workflow

# Allow one concurrent deployment
concurrency:
  group: GitHub Pages
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - "*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and to release to GitHub Releases
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-astro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install, build, and upload your site
        uses: withastro/action@v6
        with:
          path: .
          node-version: 24

  deploy-astro:
    needs: build-astro
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
