## Documentation
# https://docs.astro.build/en/guides/deploy/github/

name: HEIG-VD UPInfo Course GitHub Workflow

# Allow one concurrent deployment
concurrency:
  group: GitHub Pages
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and to release to GitHub Releases
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-presentations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate presentations with Marp
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          entrypoint: bash
          args: generate-presentations.sh

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: presentation-files
          path: |
            **/*-presentation.pdf
            **/presentation.html
          if-no-files-found: error
          retention-days: 1

  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build website with Astro
        uses: withastro/action@v6
        with:
          path: .
          node-version: 24

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: website-files
          path: dist
          if-no-files-found: error
          retention-days: 1

  generate-printable-documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate printable documents with Pandoc
        uses: docker://pandoc/latex:3-debian
        with:
          entrypoint: bash
          args: generate-printable-documents.sh

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: printable-documents-files
          path: |
            **/*.pdf
          if-no-files-found: error
          retention-days: 1

  merge-files-for-github-pages:
    runs-on: ubuntu-latest
    needs: [generate-presentations, build-website, generate-printable-documents]
    # Only run on main
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: "*-files"

      - name: Merge files
        run: |
          # Move the website files to the `public` directory
          mv website-files public

          # Move the presentation files to the `public` directory
          cp --recursive --link --update presentation-files/* public/

          # Move the printable documents to the `public` directory
          cp --recursive --link --update printable-documents-files/* public/

      - name: Upload files to GitHub Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public
          name: github-pages-artifacts

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: merge-files-for-github-pages
    # Only run on main
    if: github.ref == 'refs/heads/main'
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: github-pages-artifacts
